import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponents from "./Components/Header";
import { StoreProvider } from "./store/StoreProvider";
import { Toaster } from "react-hot-toast";
import CheckUser from "./HOC/CheckUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JIRA",
  description: "Generated by create next app",
  icons: {
    icon: "/jira.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Toaster />
          <HeaderComponents />
          <CheckUser>{children}</CheckUser>
        </body>
      </html>
    </StoreProvider>
  );
}
